trigger:
  - master

variables:
  - group: dbw-cicd-dev
  - group: dbw-cicd-prod

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/databricks-deployment.yml
    parameters:
      stage_id: "databricks_deploy_to_dev_environment"
      env: "dev"
      environment_name: $(dev-environment-name)
      databricks_host: $(dev-databricks-host)
      databricks_token: $(dev-databricks-token)
      databricks_repo_id: $(dev-databricks-repo-id)
      deploy_path: $(dev-deploy-path)

#  - template: templates/databricks-deployment.yml
#    parameters:
#      stage_id: "databricks_deploy_to_prod_environment"
#      depends_on: ["databricks_deploy_to_dev_environment"]
#      env: "prod"
#      environment_name: $(prod-environment-name)
#      databricks_host: $(prod-databricks-host)
#      databricks_token: $(prod-databricks-token)
#      databricks_repo_id: $(prod-databricks-repo-id)
#      deploy_path: $(prod-deploy-path)
